functionsDirectory = "/home/ubuntu/memearena-website/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/ubuntu/memearena-website/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm install && pnpm run build"
functions = "/home/ubuntu/memearena-website/netlify/functions"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]